
API_KEY    = "dRgQcwO7Gsihp4yVrMcfW8SajknYbKCyZEhDdhlWkUVbIjatbjJMiITADkqOLjKx"

API_SECRET = "zUV63pcVSqFIs5HqwnzusFRlADdujAsTLDz8GV3wOQ38qLlez2lCqQcEy1mreXIb"

CLAUDE_API_KEY = "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"

TESTNET = True

SYMBOL = "BTC/USDT"

RISK_PERCENT = 2

STOP_LOSS_PERCENT = 3

TAKE_PROFIT_PERCENT = 6

CHECK_INTERVAL = 60

